version: '3'
services:
  rwdb:
    container_name: mysql
    image: mysql:8
    hostname: user-db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - "/Users/minicloudsky/docker_volumes/mysql:/var/lib/mysql"